# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 
#10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued 
#terms.

def findSum

	sumOfEvenValues = 0
	fibSeq = [1, 2]
	
	while fibSeq.last <= 4000000
		fibSeq.push fibSeq[fibSeq.length - 2] + fibSeq[fibSeq.length - 1]
	end
	
	fibSeq.pop

	fibSeq.each do |number|
		if number % 2 == 0
			sumOfEvenValues = sumOfEvenValues + number
		end
	end

	puts sumOfEvenValues
end

findSum

